// Generated by CoffeeScript 2.4.1
(function() {
  var app, bodyParser, cors, express, path;

  express = require('express');

  bodyParser = require('body-parser');

  cors = require('cors');

  path = require('path');

  app = express();

  app.use(bodyParser.urlencoded({
    extended: false
  }));

  app.use(cors());

  app.set('views', path.join(__dirname, 'views'));

  // Sets the render enging to EJS
  app.set('view engine', 'ejs');

  app.get('/', function(request, response) {
    return response.render('index');
  });

  app.listen(8000);

}).call(this);
